### PR TITLE
chore: always pass era-tester CI

### PR DESCRIPTION
**Pull request by tserg**
### What I did

Always pass the era-tester CI. The red cross is misleading for a non-blocking CI.

### Commit message

```
chore: always pass era-test CI

This PR relaxes the check for era-tester CI
so that it always succeeds as a non-blocking
CI.
```

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by charles-cooper** [comment]
not sure we want this - if era tester it does indicate something is wrong (either on our end or downstream), and the red cross motivates us to fix it

**Comment by charles-cooper** [comment]
merging this -- the benefit of having visibility into the era pipeline is outweighed by not being able to see quickly if other CI jobs are failing. if we can get something like pytest's `xfail` in github actions, we can use that for this job then.

**Comment by fubuloubu** [comment]
https://stackoverflow.com/a/70048004

**Comment by charles-cooper** [comment]
> https://stackoverflow.com/a/70048004

yea that's basically what this does, but the technique just marks it as successful. github actions doesn't have a third category - "expected/allowed failure"

**Review by charles-cooper — APPROVED** [review]

**Pull request merged**
