### PR TITLE
consolidate and rename top-level modules

### PR DESCRIPTION
**Pull request by charles-cooper**
### What I did

Consolidate and clarify top level module names.

NOTE this is a draft/proposed new structure. I haven't spent the time to redo all the imports until the structure is finalized.

### How I did it

functions/ only dealt with builtin functions so it's been renamed.
interfaces/ only dealt with builtin interfaces so it's been renamed.

codegen/ was going to be a module to replace parser, but we are going to
replace parser/ entirely with another pass (name tbd), so throw it all
in together.

signatures/ had too much ast code so it went in ast/.

settings.py seemed like it belonged in compiler/
opcodes seemed like it belonged in a new folder for evm specifics.
compile_lll and optimizer seemed to belong in a new lll/ folder.

Questions:
context/ seems like it has a bunch of different stuff in it. Maybe it could be merged with ast and parser?
types/ seems like it could be merged with another typing folder.
We need a replacement for "parser", i.e. a pass between "ast" and "lll". Maybe we can just call it ir/
For clarity, we might want to put all the actual passes in a single folder. Right now ast/, lll/ and (proposed) ir/ are top-level modules but we might want compiler/ast/, compiler/lll, compiler/ir.

### Description for the changelog
Refactor internal module structure

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by fubuloubu — COMMENTED** [review]
1. `signatures` under `ast` - it should be possible to integrate this functionality into the AST a bit further. Some ideas:
  - Any external call nodes can be substituted for `raw_call` and `abi_encode` to simplify AST
  - Be able to pull ABI types from AST more directly, for generating contract ABI output

2. `functions` to `builtin_functions` - could be worth rethinking how "standard library" functions are designed/provided, especially precompiles vs. convienence functions

3. `interfaces` to `builtin_interfaces` - I really don't like how these are handled. I think they should be ABI JSON files (and added to `setup` as package data)

4. `opcodes` under `evm` - what else is gonna go under the `evm` module?

5. `lll` module - I was thinking about making this into a completely separate package, what do you think?

6. `codegen` under `parser` - do you intend on getting rid and/or merging this functionality? I kind of liked the `codegen` module to house the compiler stage that converts AST to LLL

**Comment by charles-cooper** [comment]
@fubuloubu comments inline. My intention for this PR is just to clarify the purposes of each top-level module which in turn may suggest future areas for refactoring - but this PR doesn't actually do any refactoring itself.

_1. signatures under ast - it should be possible to integrate this functionality into the AST a bit further_
- Sure, and putting signatures/ under ast/ suggests the future work. This is a top-level module renaming PR only, not a code refactoring PR.
 
_2. functions to builtin_functions - could be worth rethinking how "standard library" functions are designed/provided, especially precompiles vs. convienence functions_
- Sure. Again, this is a module-renaming PR only! I think that in the future these could go into ast/ or ir/ since these are vyper-specific builtins, but for now this is a good 'holding area' for these functions since it better describes what the module is for. (It's pretty confusing that we have like 10 modules which are named "functions" with no disambiguation).

_3. interfaces to builtin_interfaces - I really don't like how these are handled._
- Yeah, I think renaming to builtin_interfaces is the clearest thing to do for now. But again, this is a module-renaming PR and not a refactoring PR. And my comments about being a 'holding area' stand for this module as well.

_4. opcodes under evm - what else is gonna go under the evm module?_
- Anything related to EVM details. As to having a whole module for a single file, well -- having opcodes.py as a top-level file doesn't make sense because it contains implementation details specific to a backend. For instance if we add another backend which has its own opcodes.py file, it would lead to a conflict unless each backend is in its own module.

_5. lll module - I was thinking about making this into a completely separate package, what do you think?_
- Maybe I'm missing something but I think having the lll module as a top-level module is fine. Really, the core functionality of LLL in my mind is dealing with stack operations for internal vyper compilation passes, nothing more nothing less. (I know our LLL module does a lot of "stuff" right now but I intend to reduce that.) So I don't think there is enough functionality here that would merits a different package. However, if you have some ideas about this that I've missed, I think we should create a new thread offline (could be VIP format) to discuss.

_6. codegen under parser - do you intend on getting rid and/or merging this functionality?_
- My plan is to split codegen into two passes -- AST to Vyper IR, and then IR to LLL or EVM. Pretty much all the code in parser/ will either be removed or refactored and integrated into the ir/ module; the logic for putting codegen/ here for now is that eventually this functionality will live under the ir/ module. I think this makes more sense because eventually every pass (except the final one) will basically have some "codegen" functionality which generates the output for the next pass.

**Comment by iamdefinitelyahuman** [comment]
`context` should probably be named `typing` or something similar, but i didn't wanna move the existing `types` folder. The current `types` folder could become a subdirectory in `parser` to kinda designate it as the "old" types.

**Comment by charles-cooper** [comment]
@iamdefinitelyahuman based on your comments I moved context/ into ast, moved context/types up a relative level into ast/types and moved types/ into parser/. I also renamed parser/ to old_codegen/ to mark it as an old module we are getting rid of.

@fubuloubu and @iamdefinitelyahuman if it's alright with you, I'm going to use this as the basic module structure going forward.

**Comment by fubuloubu** [comment]
> @iamdefinitelyahuman based on your comments I moved context/ into ast, moved context/types up a relative level into ast/types and moved types/ into parser/. I also renamed parser/ to old_codegen/ to mark it as an old module we are getting rid of.
> 
> @fubuloubu and @iamdefinitelyahuman if it's alright with you, I'm going to use this as the basic module structure going forward.

LGTM, we'll see how it develops as you make these changes.

**Comment by fubuloubu** [comment]
p.s. can we close this PR?

**Comment by charles-cooper** [comment]
> p.s. can we close this PR?

I'm going to merge this and in general do work on the `vyper:next` branch. I'll submit a PR (to `vyper:next`) if I need a review on something.

**Comment by fubuloubu** [comment]
you shut your mouth when you're talking to me, lgtm bot

**Comment by charles-cooper** [comment]
after talking more with @iamdefinitelyahuman I realized that context/ does belong in its own module since it is pretty much a separate pass (I go back and forth on this, but for now it is a separate pass). (Also there were too many cyclic imports for me to merge them cleanly, we can revisit this at a later date.)

ast/ == parse code into AST, context/ == validate semantics of code. To that end I renamed context/ -> semantics/. I also renamed semantics/types/meta/ -> semantics/types/user/ since it deals with user-defined types -- structs, interfaces, events.

I also did a bunch of fixing imports everywhere for tests, so I'm going to force push new commits to `next` that are cleaner.

**Pull request merged**
