### PR TITLE
Add branch coverage reporting

### PR DESCRIPTION
**Pull request by fubuloubu**
https://docs.codecov.io/docs/about-code-coverage

crazy monkey

### CODE REVIEW

**Comment by fubuloubu** [comment]
Note: the large change in coverage is due to this PR enabling branch coverage, which is a stricter form of coverage many projects opt not to do.

**Comment by charles-cooper** [comment]
Seems pretty good, are there any downsides to this

**Comment by fubuloubu** [comment]
No downsides, just looks a little worse for us because branch coverage is more strict than line coverage. To give an example:
```
if condition:  # Branch coverage cares about both states of this condition
    do_something()  # Line coverage only cares that this was reached
# else - Line coverage doesn't care if the false-y scenario was executed
```

**Comment by fubuloubu** [comment]
@jacqueswww :+1: and can merge

**Pull request merged**
