### PR TITLE
feat: drop istanbul and berlin support

### PR DESCRIPTION
**Pull request by charles-cooper**
### What I did
per https://github.com/vyperlang/vyper/issues/3365,
- drop istanbul support as it is 4 years old
- drop berlin support since it will be 3 years old by the time of release

also:
- change nonreentrant key values for cancun(!)

### Commit message

```
this commit drops explicit support for the istanbul and berlin hard
forks per the three year rule suggested in VIP 3365

- istanbul hard fork was 2019-12-09, over 4 years ago
- berlin hard fork was 2021-04-15, which should be 3 years ago by the
  time of 0.4.0 release (or if we can release sooner, shortly after)

this commit also changes the nonreentrant key values for cancun (since
`PUSH0` takes 1 less byte in the bytecode).
```

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by pcaversaccio — COMMENTED** [review]
Two general comments:
- We should document the [3-year rule](https://github.com/vyperlang/vyper/issues/3365#issuecomment-1983998667) more prominently in the docs so we do our job to set expectations & we must add more prominently the currently supported EVM versions.
- We put a disclaimer that the [3-year rule](https://github.com/vyperlang/vyper/issues/3365#issuecomment-1983998667) is not set in stone forever and can change over time due changing circumstances (one scenario is that there is no new EVM version for over 3 years, or there is a cascade of numerous EVM versions within 2 years that make it hard to maintain). Thus, we should state that it's subject to change.

**Comment by charles-cooper** [comment]
> Two general comments:
> 
> * We should document the [3-year rule](https://github.com/vyperlang/vyper/issues/3365#issuecomment-1983998667) more prominently in the docs so we do our job to set expectations & we must add more prominently the currently supported EVM versions.
> * We put a disclaimer that the [3-year rule](https://github.com/vyperlang/vyper/issues/3365#issuecomment-1983998667) is not set in stone forever and can change over time due changing circumstances (one scenario is that there is no new EVM version for over 3 years, or there is a cascade of numerous EVM versions within 2 years that make it hard to maintain). Thus, we should state that it's subject to change.

https://github.com/vyperlang/vyper/pull/3843/commits/458c0981e48267a46769c84f9d313cf0d9ddbcc1#diff-69cdc09324658e05919bf7af42e6acf5a3d24c57e362497b89779838eb12a4e6R176

**Review by harkal — APPROVED** [review]

**Comment by cyberthirst** [comment]
> Two general comments:
> 
> * We should document the [3-year rule](https://github.com/vyperlang/vyper/issues/3365#issuecomment-1983998667) more prominently in the docs so we do our job to set expectations & we must add more prominently the currently supported EVM versions.
> * We put a disclaimer that the [3-year rule](https://github.com/vyperlang/vyper/issues/3365#issuecomment-1983998667) is not set in stone forever and can change over time due changing circumstances (one scenario is that there is no new EVM version for over 3 years, or there is a cascade of numerous EVM versions within 2 years that make it hard to maintain). Thus, we should state that it's subject to change.

Maybe rather than using absolute time metric, what about we rather focus on how the different L2s are doing wrt to supporting the latest EVM?

3 yrs is plenty of time to catch up - i think this window could be smaller and the maintenance overhead lowered

**Comment by pcaversaccio** [comment]
> Maybe rather than using absolute time metric, what about we rather focus on how the different L2s are doing wrt to supporting the latest EVM?
> 
> 3 yrs is plenty of time to catch up - i think this window could be smaller and the maintenance overhead lowered

I personally think it's all about expectation management and thus how we (= Vyper) set the expectations. People / Governance tend to think in time scales and not abstractions like EVM versions. New hard fork upgrades undergo governance (mostly DAO-based)  approvals on L2s and thus, it will take time in any case (the `PUSH0` case is great in that respect). Also, the largest consumers of the EVM are compilers, and dropping support for older versions can be interpreted as censoring through compilers. Cutting too early EVM versions due to fast iterations on the execution layer is also not really the way to go. Thus, we should find a good balance here to juggle these points.

**Review by cyberthirst — APPROVED** [review]

**Pull request merged**
