### PR TITLE
feat: deprecate `vyper-serve`

### PR DESCRIPTION
**Pull request by tserg**
### What I did

Deprecate `vyper-serve`.

### How I did it

Delete files.

### Commit message

```
feat: deprecate `vyper-serve`
```

### Description for the changelog

Deprecate `vyper-serve`.

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by charles-cooper** [comment]
Thank you! Maybe we should add some tests for this? Or maybe get rid of vyper serve altogether (as part of the compiler project). It could be standalone.

**Comment by fubuloubu** [comment]
> Or maybe get rid of vyper serve altogether (as part of the compiler project). It could be standalone.

We've been working on a standalone compiler service with remix (that supports any versions of vyper through VVM): https://github.com/ApeWorX/hosted-compiler

**Comment by tserg** [comment]
Shall we get rid of `vyper-serve` entirely then?

**Comment by fubuloubu** [comment]
> Shall we get rid of `vyper-serve` entirely then?

I think that makes sense. Lessens maintenance overhead on vyper

**Review by charles-cooper — APPROVED** [review]

**Pull request merged**
