### PR TITLE
perf: lazy eval of f-strings in IRnode ctor

### PR DESCRIPTION
**Pull request by charles-cooper**
25% of IR generation is in `IRnode.__repr__` due to the references to self in the f-strings for panic messages. this commit switches to using `assert`, which accomplishes the same thing, but lazily evaluating the error messages (and the code is slightly less pretty)

### Commit message

Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../blob/master/docs/style-guide.rst#best-practices-1) for what we would ideally like to see in a commit message.)

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by fubuloubu — COMMENTED** [review]
Assert statements are removed during certain optimization modes of python

https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement

**Comment by charles-cooper** [comment]
> Assert statements are removed during certain optimization modes of python
> 
> https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement

i'm aware of this, but i don't think people are really running vyper with asserts disabled, and we shouldn't support that behavior. also, these are sanity checks for compiler-internal invariants, not validating user data, so we don't actually expect to trip these cases.

**Comment by charles-cooper** [comment]
the other way to do this is to actually inline all those checks, to be like
```
if not <cond>:
    raise CompilerPanic(...)
```
but i opted not to do this because the logic seemed less clear from a readability perspective.

**Comment by fubuloubu** [comment]
> > Assert statements are removed during certain optimization modes of python
> > 
> > https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement
> 
> i'm aware of this, but i don't think people are really running vyper with asserts disabled, and we shouldn't support that behavior anyway. in addition, these are sanity checks for compiler-internal invariants, not validating user data, so we don't actually expect to trip these cases.

Alright, if this is the case (and it is documented), I'm on board with it since if you optimized out (which we don't really have control over how someone uses the library) it should not cause an issue, unless vyper is missing a good test case (basically we don't expect users to run into these scenarios)

**Comment by charles-cooper** [comment]
> Alright, if this is the case (and it is documented), I'm on board with it since if you optimized out (which we don't really have control over how someone uses the library) it should not cause an issue, unless vyper is missing a good test case (basically we don't expect users to run into these scenarios)

we also have many other uses of `assert` in the codebase

**Comment by charles-cooper** [comment]
another way to do it is to allow the formatting to happen inside the helper function
```
def _check(cond, fstr, *args):
    if not cond:
        raise CompilerPanic(fstr.format(*args))
```
and then used like
```
_check(cond, "xyz {}", arg1)
```

but i'm leaning against this because f-strings have better support in our lint setup.

**Review by fubuloubu — APPROVED** [review]

**Pull request merged**
