### PR TITLE
fix[lang]: fix `uses` analysis for nonreentrant functions

### PR DESCRIPTION
**Pull request by charles-cooper**
fixes https://github.com/vyperlang/vyper/issues/3922

### Commit message

```
`uses` analysis ignores nonreentrant functions, even though those that
(implicitly) use state.

this commit adds checks both for internally (called) and external
(exported) modules

misc/refactor:
- factor out `uses_state()` util
- rename `validate_functions` to more accurate `analyze_functions`
- improve locality of exceptions thrown in check_module_uses
```

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by pcaversaccio — COMMENTED** [review]
Right now the error message is very generic:

```console
vyper.exceptions.ImmutableViolation: Cannot access `lib` state!
```

In most cases, this will work but it might be confusing if a `nonreentrant` decorator is used because it might not be obvious. I would recommend either issuing a separate error message if a `nonreentrant` decorator is used or amend the currently existing generic error message.

Furthermore, the compiler currently doesn't raise if block and transaction properties (e.g. `block.number` or `msg.gas`) or `self` / `self.balance` is used:

```vy
# lib.vy
@internal
def _foo() -> address:
    return self

# main.vy
import lib

@external
def foo() -> address:
    return lib._foo()
```

Q: Should we treat these properties as well as state accesses in an extended sense, since e.g. `self` is an `immutable` variable in the strict sense as it resolves at construction time and not at compile-time.

**Review by cyberthirst — APPROVED** [review]
lgtm

**Comment by cyberthirst** [comment]
> Should we treat these properties as well as state accesses in an extended sense, since e.g. self is an immutable variable in the strict sense as it resolves at construction time and not at compile-time

I'd say we already do that, eg the following contracts won't compile:
```vyper
# ex1
@external
@pure
def foo() -> address:
    return self
    
 # ex2
 @external
@pure
def foo() -> uint256:
    return block.number
```

**Comment by charles-cooper** [comment]
> Q: Should we treat these properties as well as state accesses in an extended sense, since e.g. self is an immutable variable in the strict sense as it resolves at construction time and not at compile-time.

no, these have more to do with environment access (you can think of them like "intrinsics" or "syscalls") and are not directly related to the language's module system

**Comment by charles-cooper** [comment]
> Right now the error message is very generic:
> 
> ```
> vyper.exceptions.ImmutableViolation: Cannot access `lib` state!
> ```
> 
> In most cases, this will work but it might be confusing if a `nonreentrant` decorator is used because it might not be obvious. I would recommend either issuing a separate error message if a `nonreentrant` decorator is used or amend the currently existing generic error message.

opted for the later: https://github.com/vyperlang/vyper/pull/3927/commits/eaa59886274ac5e6af41c86a2e7d3d8d47f17c86

**Review by pcaversaccio — APPROVED** [review]

**Pull request merged**
