### PR TITLE
fix: sigdata array input change to uint256[5][3]

### PR DESCRIPTION
**Pull request by mmsaki**

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]

**Comment by charles-cooper** [comment]
@mmsaki looks like this breaks some tests?

**Comment by mmsaki** [comment]
@charles-cooper the test_approve in [tests/examples/wallet/test_](https://github.com/vyperlang/vyper/blob/master/tests/examples/wallet/test_wallet.py) failed. I wish to look into it but I am still catching up on how to navigate through the docs.

**Review by charles-cooper — CHANGES_REQUESTED** [review]
@mmsaki could you please explain why the change is needed?

**Comment by charles-cooper** [comment]
I don't think this change is right. the order of array indexes are reversed in vyper compared to most languages. I'm open to having that changed, but we can't just change the tests without actually changing the implementation.

**Pull request closed without merging**
