### PR TITLE
feat: publish immutables layout

### PR DESCRIPTION
**Pull request by charles-cooper**
### What I did
publish immutables layout. since the output is a single dict of variable names (see below for ex.), I was a bit concerned about collisions between immutables and storage variables, so I went ahead and blocked those.

```json
{"foo": {"type": "uint256", "location": "code", "offset": 0, "length": 32}, "x": {"type": "uint256", "location": "storage", "slot": 0}}
```

### How I did it
add code offsets dict to the `-f layout` output

### How to verify it
try
```vyper
vyper -f layout /dev/stdin <<EOF
x: uint256
y: immutable(uint256)
@external
def __init__():
    y = 1
EOF
```

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]

**Review by fubuloubu — APPROVED** [review]

**Review by fubuloubu — APPROVED** [review]

**Comment by charles-cooper** [comment]
kind of wonder if we should publish as two separatel dicts. e.g.
```
{
  "storage": {"x": ...}, {"y": ...},
  "code": {"a": ...}, {"b": ...},
}
```
@fubuloubu thoughts?

**Comment by fubuloubu** [comment]
> kind of wonder if we should publish as two separatel dicts. e.g.
> ```
> {
>   "storage": {"x": ...}, {"y": ...},
>   "code": {"a": ...}, {"b": ...},
> }
> ```
> @fubuloubu thoughts?

Are collisions even allowed?

**Comment by charles-cooper** [comment]
> Are collisions even allowed?

there was a case where they were allowed, but I blocked them in this PR. but we might not always block.

**Comment by fubuloubu** [comment]
> > Are collisions even allowed?
> 
> there was a case where they were allowed, but I blocked that case in this PR. but we might not always block.

I think collisions should not be allowed here. It's sort of like a `global` var

**Comment by charles-cooper** [comment]
meeting notes: separate into two dicts

**Review by fubuloubu — APPROVED** [review]

**Pull request merged**
