### PR TITLE
fix: enum variables accessed via `self.`

### PR DESCRIPTION
**Pull request by charles-cooper**
### What I did
UX fix: enum members accessed directly with `self` would throw a compiler panic

### How I did it
fix namespace detection in codegen

### How to verify it
see tests

### Commit message
enum members accessed directly with `self` would throw a compiler panic

### Cute Animal Picture

image

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]
Maybe a few more tests, but otherwise looking good

**Comment by charles-cooper** [comment]
what kind of tests?

**Comment by fubuloubu** [comment]
> what kind of tests?

Maybe public, accessing inside an internal method, that sort of thing

**Comment by charles-cooper** [comment]
@fubuloubu see https://github.com/vyperlang/vyper/pull/2998/commits/82e1d3603300d3b041a5b868ef9ee5e50fb7b4d2

**Review by fubuloubu — APPROVED** [review]

**Pull request merged**
