### PR TITLE
Update pull request template

### PR DESCRIPTION
**Pull request by charles-cooper**
Since we switched to squash/merge, the commit message is generated at
the time of merging the PR. This template adds space for the PR
submitter to write a commit message that the merger can then copy/paste
into github's UI.

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by fubuloubu — COMMENTED** [review]
Overall, I feel like this template is pretty verbose and might turn away new contributors. This template might be good for PRs that more senior contributors might make, but for newcomers there is a lot of information here

I think it would be important to pull out key tidbits that we'd want to have and enforce them in the CI, or in the template through different sections of the PR. I would minimize more eliminate the amount of context a contributor would have to give to have their PR accepted, so that the barrier is smaller and the reasoning behind why the information is necessary is obvious

**Comment by charles-cooper** [comment]
ah ok. how about if we just say that the section is optional, and link to the [style guide](https://vyper.readthedocs.io/en/latest/style-guide.html#id3) for more context?

**Comment by charles-cooper** [comment]
@fubuloubu see https://github.com/vyperlang/vyper/blob/978d423fad51e5f89aec4441849a6a51832682a3/.github/PULL_REQUEST_TEMPLATE.md, what do you think?

**Review by fubuloubu — APPROVED** [review]
Perfect!

**Pull request merged**
