### PR TITLE
feat[lang]: implement export bundles

### PR DESCRIPTION
**Pull request by charles-cooper**
### What I did
implement exports and export bundles.

export bundles are a way for library authors to group together external
functions in the ABI

example:
```vyper
bundle: IERC_X  # declare a bundle

@internal
def foo() -> uint256:
    return 10

@external
def extern1():
    pass

@external
@Bundle(IERC_X)
def extern2():
    pass

@external
@Bundle(IERC_X, bind=False)  # extern3 ok to export on its own
def extern3():
    pass

@external
@Bundle(IERC_X, bind=True)  # extern4 cannot be exported on its own!
def extern4():
    pass
```

it can be used like this:
```vyper
import library

exports: library.IERC_X

@external
def library_foo() -> uint256:
    return library.foo()
```

or like this:
```vyper
import library

exports: library.extern1, library.extern2

@external
def library_foo() -> uint256:
    return library.foo()
```

but not like this(!):

```vyper
import library

exports: library.extern4  # raises StructureException

@external
def library_foo() -> uint256:
    return library.foo()
```

### Commit message

Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../master/docs/style-guide.rst#best-practices-1) for what we would ideally like to see in a commit message.)

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by fubuloubu** [comment]
Would prefer that we create less language keywords so we can namespace better:

```vyper
from vyper.packaging import Bundle
IERC_X: Bundle  = Bundle() # declare a bundle

@internal
def foo() -> uint256:
    return 10

@external
def extern1():
    pass

@external
@IERC_X.add()
def extern2():
    pass

@external
@IERC_X.add(bind=False)  # extern3 ok to export on its own
def extern3():
    pass

@external
@IERC_X.add(bind=True)  # extern4 cannot be exported on its own!
def extern4():
    pass
```

**Comment by charles-cooper** [comment]
> Would prefer that we create less language keywords so we can namespace better:
> 
> ```vyper
> from vyper.packaging import Bundle
> IERC_X: Bundle  = Bundle() # declare a bundle
> 
> @internal
> def foo() -> uint256:
>     return 10
> 
> @external
> def extern1():
>     pass
> 
> @external
> @IERC_X.add()
> def extern2():
>     pass
> 
> @external
> @IERC_X.add(bind=False)  # extern3 ok to export on its own
> def extern3():
>     pass
> 
> @external
> @IERC_X.add(bind=True)  # extern4 cannot be exported on its own!
> def extern4():
>     pass
> ```

`export` and `bundle` are not protected keywords though.

i also don't really like putting Bundle behind a namespace because:
- choosing what to expose in the ABI should be a first class concept in the language
- the proposed syntax looks like it's part of the "standard library" and like you could implement your own export semantics as a decorator. you can't, it's a compiler intrinsic

**Comment by fubuloubu** [comment]
Well, would say that `bundle` as a keyword exists in multiple EIPs and would be careful about enshrining its use

**Comment by charles-cooper** [comment]
I mean we could pick another name. But my point is it's not a keyword, you can still define variables and functions etc named `bundle`.

**Comment by fubuloubu** [comment]
> I mean we could pick another name. But my point is it's not a keyword, you can still define variables and functions etc named `bundle`.

I can create a function or state variable named `implements` too?

**Comment by charles-cooper** [comment]
> I can create a function or state variable named `implements` too?

yep

**Comment by fubuloubu** [comment]
> > I can create a function or state variable named `implements` too?
> 
> yep

So, these two don't conflict?

```vyper
# interface check
implements: ERC20

# state variable
implements: ERC20
```

**Comment by charles-cooper** [comment]
> So, these two don't conflict?
> 
> ```vyper
> # interface check
> implements: ERC20
> 
> # state variable
> implements: ERC20
> ```

aha yea they use a similar AST node as for state variable declarations so not those, but everything else -- function names, local variables, names of things
```vyper
@external
def implements():
    pass
```
```vyper
event implements:
    pass
```
```vyper
@external
def foo(implements: uint256):
    pass
```

**Comment by charles-cooper** [comment]
closing this as superseded (for now) by https://github.com/vyperlang/vyper/pull/3786 and the spec could use some polishing, will revisit in 0.4.1

**Pull request closed without merging**
