### PR TITLE
Optimize safe mul

### PR DESCRIPTION
**Pull request by charles-cooper**
### What I did
Optimize the multiplication operation so it takes less gas and fewer bytes in the code. The assembly goes from
```
DUP1 DUP3 MUL DUP3 ISZERO DUP3 DUP5 DUP4 DIV EQ OR ISZERO _sym_revert0 JUMPI DUP1 SWAP1 POP SWAP1 POP SWAP1 POP
```
to
```
DUP1 DUP3 MUL DUP3 DUP2 DIV DUP3 DUP3 DIV MUL XOR _sym_revert0 JUMPI MUL
```
The gas taken goes from ~~67~~ 69 to ~~46~~ 54, and the bytes taken goes from 23 to 16.

EDIT: using mulmod is even faster: 50 gas / 15 bytes.
```
DUP2 DUP2 MUL PUSH1 0x0 NOT DUP4 DUP4 MULMOD LT _sym_revert0 JUMPI MUL
```

I am leaving this as a draft because it's unclear to me whether it's worth micro-optimizing code like this if we are planning better LLL optimizations (which might render this moot) in the future.

### How I did it

There are three reasons this is faster.

1) Handrolled assembly instead of `with` operations which always result in extra POPs
2) In the handrolled assembly, it reduces the number of stack operations by actually calculating the result twice. Since the operands are used multiple times, they need to be DUPed anyway, and caching the result of MUL + reordering them in the stack takes more instructions than just recalculating MUL.
3) Also, the algorithm is essentially changed from

```
(seq
  p = x * y
  assert (p/x == y | x==0)
  p
)
```
to
```
(seq
  p = x * y
  y1 = p/x
  x1 = p/y
  assert(x1 * y1 == p)
  x * y
)
```
Despite using more arithmetic operations, this is (hilariously) faster because we can use the contrapositive XOR JUMPI sequence to check equality (whereas `(a==b) | c` basically requires an extra ISZERO -- `a b EQ c OR ISZERO`).

EDIT: new routine is
```
(seq
  p = x * y
  p1 = mulmod(x, y, not(0))
  assert(p >= p1)
  x*y
)
```

### How to verify it
:thinking: 

### Cute Animal Picture

image

### CODE REVIEW

**Comment by charles-cooper** [comment]
There is a failing test but I think it's a type mistake, not a logical mistake. I'll fix it if we decide this is a good idea.

**Comment by hrkrshnn** [comment]
```
(seq
  p = x * y
  p1 = mulmod(x, y, not(0))
  assert(p == p1)
  x*y
)
```
If `x * y = not(0)`, this won't be true, right? For `x = 340282366920938463463374607431768211455` and `y = 340282366920938463463374607431768211457`, `x * y = not(0)`, but `mulmod(x, y, not(0)) = 0`.

**Comment by charles-cooper** [comment]
> ```
> (seq
>   p = x * y
>   p1 = mulmod(x, y, not(0))
>   assert(p == p1)
>   x*y
> )
> ```
> 
> If `x * y = not(0)`, this won't be true, right? For `x = 340282366920938463463374607431768211455` and `y = 340282366920938463463374607431768211457`, `x * y = not(0)`, but `mulmod(x, y, not(0)) = 0`.

That's true, this is a bug in my logic.

Hmm I suppose we could correct for that case using something like `x * y >= (mulmod(x, y, not(0))` but it may be that reverting to my first technique is better.

**Comment by charles-cooper** [comment]
@hrkrshnn good catch, fixed in 166e5435e379667857299abbb475be859759ea6f

**Comment by hrkrshnn** [comment]
Unfortunately, changing to `>=` won't help either. Take `x = 2**256 - 1` and `y = 2`, then `x * y` overflows and evaluates to `2**256 - 2`, but `mulmod(x, y, not(0)) = 0`.

**Comment by charles-cooper** [comment]
> Unfortunately, changing to `>=` won't help either. Take `x = 2**256 - 1` and `y = 2`, then `x * y` overflows and evaluates to `2**256 - 2`, but `mulmod(x, y, not(0)) = 0`.

Oof I think you're right. I am going to revisit this a little more slowly.

**Comment by charles-cooper** [comment]
superseded by https://github.com/vyperlang/vyper/pull/3659

**Pull request closed without merging**
