### PR TITLE
docs: update resources section

### PR DESCRIPTION
**Pull request by pcaversaccio**
### What I did

I made the following changes in the `resources.rst` file:
- Added my Vyper GitHub list (the reason is that many have already asked where to find such a list)
- I replaced the `VyperDeployer` for Foundry with my 🐍 snekmate version as the other one is outdated (see https://github.com/0xKitsune/Foundry-Vyper/issues/7#issuecomment-1714346954)
- I added Titanoboa to the references
- I remove the dunder for the links as this is unnecessary and `_` is enough
- Fixed some additional small chore

### How I did it

N/A.

### How to verify it

N/A

### Commit message

```console
docs: update resources section
```

### Description for the changelog

docs: update resources section

### Cute Animal Picture

image

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]
Maybe consider moving the old link to the bottom

**Comment by pcaversaccio** [comment]
> Maybe consider moving the old link to the bottom

Yup, makes sense indeed. Addressed via https://github.com/vyperlang/vyper/pull/3656/commits/8175ada95223ced6fe51863574e5be9be65fdcdf.

**Review by fubuloubu — APPROVED** [review]

**Comment by charles-cooper** [comment]
seems fine. should we add in a link to titanoboa at some point?

**Comment by pcaversaccio** [comment]
> seems fine. should we add in a link to titanoboa at some point?

Sure, done via https://github.com/pcaversaccio/vyper/commit/6e8ba244edc7194a5a101f58a717908e08e8d931.

**Review by charles-cooper — APPROVED** [review]

**Pull request merged**
