### PR TITLE
chore: support Python 3.10

### PR DESCRIPTION
**Pull request by fubuloubu**
### What I did
fixes: #2548

### How I did it
github ui

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by istankovic** [comment]
@fubuloubu any news on this?

**Comment by fubuloubu** [comment]
`blake2b-py` does not have release binaries yet for Python 3.10

Also... need to set up eth-tester to not use `blake2b-py`...

**Comment by charles-cooper** [comment]
The blake2b-py dependency was fixed in https://github.com/ethereum/py-evm/pull/2012 but we can't upgrade py-evm yet because of a dependency conflict in web3.py. Tracking in https://github.com/ethereum/web3.py/issues/2295

**Review by charles-cooper — APPROVED** [review]
approved pending tests passing

**Pull request merged**
