### PR TITLE
feat[lang]: export interfaces

### PR DESCRIPTION
**Pull request by charles-cooper**
### How to verify it
examples:
```vyper
# example1.vy

from snekmate.tokens import ERC20 as base_token
initializes: base_token

exports: base_token.__interface__

@deploy
def __init__():
    base_token.__init__("My Token", "TOK", 100_000_000, "My DApp", "v0.0.1")
```

```vyper
# example2.vy

from snekmate.tokens import ERC20 as base_token

from ethereum.ercs import IERC20

implements: base_token.IERC20
initializes: base_token

exports: base_token.IERC20

@deploy
def __init__():
    base_token.__init__("My Token", "TOK", 100_000_000, "My DApp", "v0.0.1")
```

### Commit message

````
this commit allows exporting of `module.<interface>`, and also adds
`module.__interface__` which gives the interface type of the module.
in particular, this makes it easier for users to export all functions
from a module, since they do not need to list out every single function
manually.

note that since `module.__interface__` is actually an interface type, it
can theoretically be used in type expressions, e.g.,
```vyper
    x: module.__interface__ = module.__interface__(msg.sender)
```

however, it doesn't work yet as some additional work is required to
properly thread the type into the type analysis system
(see related: GH #3943).

this commit includes the restriction that only `implement`ed interfaces
can be exported, this makes the most sense from a UX / user intuition
perspective.
````

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by fubuloubu — CHANGES_REQUESTED** [review]
Add at least a few tests

**Comment by cyberthirst** [comment]
this test crashes the compiler (btw it tries to test selector clashes when exporting via interfaces, though the issue seems unrelated)

```python
    ifoo = """
@external
def gsf():
    ...
    """
    lib1 = """
import ifoo

@external
@view
def tgeo() -> uint256:
    return 1
    """
    main = """
import lib1

exports: lib1.ifoo
    """
    input_bundle = make_input_bundle({"lib1.vy": lib1, "ifoo.vyi": ifoo})
    c = get_contract(main, input_bundle=input_bundle)
```
```
.0 = <dict_valueiterator object at 0x120977510>

    funcs = [
>       module_exposed_fns[f.name] for f in info.typ.functions.values() if f.is_external
    ]
E   vyper.exceptions.CompilerPanic: unhandled exception 'gsf'
E   
E     line 4:0 
E          3
E     ---> 4 exports: lib1.ifoo
E     -------^
E          5
E   
```

**Comment by charles-cooper** [comment]
> this test crashes the compiler (btw it tries to test selector clashes when exporting via interfaces, though the issue seems unrelated)

fixed in https://github.com/vyperlang/vyper/pull/3919/commits/6650768d796dd9122b609945b4e7807f179b04f3

**Review by cyberthirst — APPROVED** [review]

**Review by pcaversaccio — COMMENTED** [review]
There is currently an issue wrt the `__init__` handling:

```console
During handling of the above exception, another exception occurred:

vyper.exceptions.CompilerPanic: unhandled exception '__init__'
```

To replicate: use my [`TimelockControllerMock.vy`](https://github.com/pcaversaccio/snekmate/blob/modules/src/snekmate/governance/mocks/TimelockControllerMock.vy) and replace the `exports` with:

```vyper
exports: tc.__interface__
```

**Review by pcaversaccio — APPROVED** [review]
Tested on snekmate contracts and tests pass. I recommend adding an additional test for `__default__` function. Otherwise, lgtm.

**Comment by pcaversaccio** [comment]
> There is currently an issue wrt the `__init__` handling:
> 
> ```
> During handling of the above exception, another exception occurred:
> 
> vyper.exceptions.CompilerPanic: unhandled exception '__init__'
> ```
> 
> To replicate: use my [`TimelockControllerMock.vy`](https://github.com/pcaversaccio/snekmate/blob/modules/src/snekmate/governance/mocks/TimelockControllerMock.vy) and replace the `exports` with:
> 
> ```vyper
> exports: tc.__interface__
> ```

Fixed via https://github.com/vyperlang/vyper/pull/3919/commits/0450173793975ac87852f3b7e09cb97a37bd764c.

**Pull request merged**
