### PR TITLE
feat: make built-in `ERC721` interface functions `payable`

### PR DESCRIPTION
**Pull request by pcaversaccio**
### What I did

In the official [EIP-721](https://eips.ethereum.org/EIPS/eip-721), the following functions are declared as `payable`:

```solidity
function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) external payable;
function safeTransferFrom(address _from, address _to, uint256 _tokenId) external payable;
function transferFrom(address _from, address _to, uint256 _tokenId) external payable;
function approve(address _approved, uint256 _tokenId) external payable;
```

### How I did it

I changed the functions `safeTransferFrom(address,address,uint256)`, `safeTransferFrom(address,address,uint256,bytes)`, `transferFrom(address,address,uint256)`, and `approve(address,uint256)` to be `payable`.

Fixes https://github.com/vyperlang/vyper/issues/3096.

### How to verify it

Check the built-in interface and example code.

### Commit message

```
💵 feat: make built-in `ERC721` interface functions `payable`

The built-in `ERC721` interface functions `safeTransferFrom(address,address,uint256)`,
`safeTransferFrom(address,address,uint256,bytes)`, `transferFrom(address,address,uint256)`,
and `approve(address,uint256)` are now `payable`.
```

### Description for the changelog

The built-in `ERC721` interface functions `safeTransferFrom(address,address,uint256)`, `safeTransferFrom(address,address,uint256,bytes)`, `transferFrom(address,address,uint256)`, and `approve(address,uint256)` are now `payable`.

### Cute Animal Picture

image

### CODE REVIEW

**Review by charles-cooper — APPROVED** [review]
lgtm, @fubuloubu thoughts?

**Review by fubuloubu — APPROVED** [review]
The spec says payable, so I guess these should be payable

Don't really understand why they're payable lol

**Comment by charles-cooper** [comment]
thanks, set to merge. @pcaversaccio please in the future, no emojis in PR titles.

**Comment by pcaversaccio** [comment]
Understood ser 👍 @charles-cooper

**Comment by pcaversaccio** [comment]
> Don't really understand why they're payable lol

Maybe the motivation was driven by royalty payments @fubuloubu? honestly, idk

**Pull request merged**
