### PR TITLE
feat[lang]!: make internal decorator optional

### PR DESCRIPTION
**Pull request by charles-cooper**
### What I did
per title

### How to verify it
updated a couple tests for it

### Commit message

```console
make `@internal` decorator optional. since functions can be imported
now, the `@internal` decorator could be confusing UX, since it is not
clear (without referencing docs) whether `@internal` means "hidden from
importers of this module", or "not included in the selector table". with
this commit, functions don't need a visibility marker, and are just
internal by default.
```

### Cute Animal Picture

image

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]

**Comment by cyberthirst** [comment]
could this be any problem wrt to integrity hash in archives?

**Comment by charles-cooper** [comment]
> could this be any problem wrt to integrity hash in archives?

i don't think so, no. the integrity hash is based on source hash. so you can have multiple sources which compile to the same bytecode, but this is already the case (e.g. comments change hash but not bytecode)

**Review by fubuloubu — APPROVED** [review]

**Comment by cyberthirst** [comment]
why do we allow `@nonreentrant + @view`? is it read-only reentrancy?

**Comment by cyberthirst** [comment]
why not remove
https://github.com/vyperlang/vyper/blob/9c157c2822b7efa5449e2c2d320a2797c8c2839e/vyper/semantics/types/function.py#L770-L771

**Comment by cyberthirst** [comment]
contracts like this
```
def __init__():
    pass
```
will throw `vyper.exceptions.FunctionDeclarationException: Constructor must be marked as `@deploy`, not `@internal`` which is a bit wierd

**Comment by cyberthirst** [comment]
did we update the docs to reflect this feature?

**Comment by charles-cooper** [comment]
> did we update the docs to reflect this feature?

yes, in https://github.com/vyperlang/vyper/pull/3947

**Comment by charles-cooper** [comment]
> contracts like this
> 
> ```
> def __init__():
>     pass
> ```
> 
> will throw
> 
> ```
>  vyper.exceptions.FunctionDeclarationException: Constructor must be marked as `@deploy`, not `@internal`
> ```
> 
> which is a bit wierd

https://github.com/vyperlang/vyper/pull/4040/commits/0a48a56d255d91fbc3853f6ebfca59f4a2d0371a

**Comment by charles-cooper** [comment]
> why not remove
> 
> https://github.com/vyperlang/vyper/blob/9c157c2822b7efa5449e2c2d320a2797c8c2839e/vyper/semantics/types/function.py#L770-L771

https://github.com/vyperlang/vyper/pull/4040/commits/9f679b285775d9a70889627a803c6574adb2f8d1

**Comment by charles-cooper** [comment]
> why do we allow `@nonreentrant + @view`? is it read-only reentrancy?

yes, #2921

**Review by cyberthirst — APPROVED** [review]

**Pull request merged**
