### PR TITLE
fix[codegen]: fix double eval of start in range expr

### PR DESCRIPTION
**Pull request by cyberthirst**
### What I did
- fix of: https://github.com/vyperlang/vyper/issues/3964

### How I did it
- cache the start argument to the stack

### How to verify it
- added a double eval test

### Commit message

Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../master/docs/style-guide.rst#best-practices-1) for what we would ideally like to see in a commit message.)

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by charles-cooper — APPROVED** [review]

**Comment by charles-cooper** [comment]
we should have tests for both 1 and 2 argument cases

**Comment by charles-cooper** [comment]
also this seems fine, but didn't we just add a fence for `pop()`? this has a performance penalty as well.

**Comment by cyberthirst** [comment]
> we should have tests for both 1 and 2 argument cases

addressed in: https://github.com/vyperlang/vyper/pull/4033/commits/8b5b364d99448de5df69f01edb1b12f934dc17e8

**Comment by cyberthirst** [comment]
> also this seems fine, but didn't we just add a fence for `pop()`? this has a performance penalty as well.

as discussed, it's a question of panicking for certain classes of contracts vs having some perf penalty

eg contracts like this wouldn't compile without the cache
```vyper

@internal
@view
def bar() -> uint256:
    return 0

@external
def foo():
    for i:uint256 in range(self.bar(), 5, bound = 3):
        pass
```

**Review by charles-cooper — APPROVED** [review]

**Pull request merged**
