### PR TITLE
modified event declaration syntax to resemble that of struct

### PR DESCRIPTION
**Pull request by realjohnward**
### What I did
modified event declaration syntax to resemble that of struct in docs, examples, etc.

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by fubuloubu** [comment]
I really like how much cleaner the updated syntax is looking. @iamdefinitelyahuman is currently working on type checking, which touches this code, so he may be able to make use of your work here or advise you on further steps to take to complete this implementation.

Thank you for taking a first shot!

**Comment by realjohnward** [comment]
No problem @fubuloubu ! I'll be working on this more later today, I've made good progress since the last commit. @iamdefinitelyahuman Do you have any suggestions on how I should move forward?

**Comment by iamdefinitelyahuman** [comment]
@realjohnward thanks for your contribution on this so far!  As @fubuloubu said, the work I'm doing will end up affecting a lot of the logic in `vyper/parser`. Enacting the change to events will also involve work in that area, but it could end up that my changes mean a lot of that code gets refactored away in the near future.  So maybe best to hold off on that area for now.

**Comment by realjohnward** [comment]
@iamdefinitelyahuman No problem at all, always happy to help!

**Comment by fubuloubu** [comment]
Deprecated in favor of work in #1864 (after type checking has been merged)

**Pull request closed without merging**
