### PR TITLE
WIP: RLP decode tx inject

### LINKED ISSUE #522: Providing an API like `get_rlp_decoder_tx_hex()` for developers using RLPList to get rid of hardcoded hex in code
* viper Version: 0.0.2
* pyethereum Version: 2.1.0
* OS: mac os
* Python Version (python --version): 3.6.0
* Environment (output of `pip freeze`):
```shell
argh==0.26.2
asn1crypto==0.23.0
astroid==1.5.3
attrs==17.3.0
bitcoin==1.1.42
bumpversion==0.5.3
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.4
click==6.7
coincurve==6.0.0
colorama==0.3.9
coverage==4.4.1
coveralls==1.1
cytoolz==0.8.2
decorator==4.1.2
docopt==0.6.2
eth-testrpc==1.3.3
ethereum==2.1.0
ethereum-abi-utils==0.4.4
ethereum-keyfile==0.3.0
ethereum-keys==0.1.0a7
ethereum-serpent==2.0.2
ethereum-tester==0.1.0b2
ethereum-utils==0.6.0
flake8==3.4.1
flaky==3.4.0
future==0.16.0
graphviz==0.8
hypothesis==3.38.0
idna==2.5
isort==4.2.15
json-rpc==1.10.8
```

### What's your issue about?
Currently if we want to use `RLPList` in viper code, we have to install `rlp_decoder` in advance.
Like this
```python
viper_rlp_decoder_tx = rlp.decode(utils.parse_as_bin("0xf9035b808506fc23ac0083045ef88080b903486103305660006109ac5260006109cc527f0100000000000000000000000000000000000000000000000000000000000000600035046109ec526000610a0c5260006109005260c06109ec51101515585760f86109ec51101561006e5760bf6109ec510336141558576001610a0c52610098565b60013560f76109ec51036020035260005160f66109ec510301361415585760f66109ec5103610a0c525b61010060016064818352015b36610a0c511015156100b557610291565b7f0100000000000000000000000000000000000000000000000000000000000000610a0c5135046109ec526109cc5160206109ac51026040015260016109ac51016109ac5260806109ec51101561013b5760016109cc5161044001526001610a0c516109cc5161046001376001610a0c5101610a0c5260216109cc51016109cc52610281565b60b86109ec5110156101d15760806109ec51036109cc51610440015260806109ec51036001610a0c51016109cc51610460013760816109ec5114156101ac5760807f01000000000000000000000000000000000000000000000000000000000000006001610a0c5101350410151558575b607f6109ec5103610a0c5101610a0c5260606109ec51036109cc51016109cc52610280565b60c06109ec51101561027d576001610a0c51013560b76109ec510360200352600051610a2c526038610a2c5110157f01000000000000000000000000000000000000000000000000000000000000006001610a0c5101350402155857610a2c516109cc516104400152610a2c5160b66109ec5103610a0c51016109cc516104600137610a2c5160b66109ec5103610a0c510101610a0c526020610a2c51016109cc51016109cc5261027f565bfe5b5b5b81516001018083528114156100a4575b5050601f6109ac511115155857602060206109ac5102016109005260206109005103610a0c5261010060016064818352015b6000610a0c5112156102d45761030a565b61090051610a0c516040015101610a0c51610900516104400301526020610a0c5103610a0c5281516001018083528114156102c3575b50506109cc516109005101610420526109cc5161090051016109005161044003f35b61000461033003610004600039610004610330036000f31b2d4f"), Transaction)
```
Once the `rlp_decoder` tx is updated, we have to change the hex manually, otherwise error occurs due to the fact that the address of the contract changes.

### How can it be fixed?

I think it will be better if we introduce a function like `get_rlp_decoder_tx_hex()` in viper, which outputs the hex of the `rlp_decoder` transaction.
The most simple one like(for simplicity, just assume it is located in the `viper/utils.py`, though it might not be the best location of the function)
```python
def get_rlp_decoder_tx_hex():
    return "0xf9035b808506fc23ac0083045ef88080b903486103305660006109ac5260006109cc527f0100000000000000000000000000000000000000000000000000000000000000600035046109ec526000610a0c5260006109005260c06109ec51101515585760f86109ec51101561006e5760bf6109ec510336141558576001610a0c52610098565b60013560f76109ec51036020035260005160f66109ec510301361415585760f66109ec5103610a0c525b61010060016064818352015b36610a0c511015156100b557610291565b7f0100000000000000000000000000000000000000000000000000000000000000610a0c5135046109ec526109cc5160206109ac51026040015260016109ac51016109ac5260806109ec51101561013b5760016109cc5161044001526001610a0c516109cc5161046001376001610a0c5101610a0c5260216109cc51016109cc52610281565b60b86109ec5110156101d15760806109ec51036109cc51610440015260806109ec51036001610a0c51016109cc51610460013760816109ec5114156101ac5760807f01000000000000000000000000000000000000000000000000000000000000006001610a0c5101350410151558575b607f6109ec5103610a0c5101610a0c5260606109ec51036109cc51016109cc52610280565b60c06109ec51101561027d576001610a0c51013560b76109ec510360200352600051610a2c526038610a2c5110157f01000000000000000000000000000000000000000000000000000000000000006001610a0c5101350402155857610a2c516109cc516104400152610a2c5160b66109ec5103610a0c51016109cc516104600137610a2c5160b66109ec5103610a0c510101610a0c526020610a2c51016109cc51016109cc5261027f565bfe5b5b5b81516001018083528114156100a4575b5050601f6109ac511115155857602060206109ac5102016109005260206109005103610a0c5261010060016064818352015b6000610a0c5112156102d45761030a565b61090051610a0c516040015101610a0c51610900516104400301526020610a0c5103610a0c5281516001018083528114156102c3575b50506109cc516109005101610420526109cc5161090051016109005161044003f35b61000461033003610004600039610004610330036000f31b2d4f"
```

In the code which need `rlp_decoder` installing:
```python
viper_rlp_decoder_tx = rlp.decode(utils.parse_as_bin(viper.utils.get_rlp_decoder_tx_hex()), Transaction)
viper_rlp_decoder_addr = viper_rlp_decoder_tx.creates
```

#### Cute Animal Picture
23905669_813377348856668_3421158803172330292_n

### PR DESCRIPTION
**Pull request by jacqueswww**
### What I did
Fixes #522 

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by fubuloubu** [comment]
Is there any way to get rid of this pre-deployed library entirely? I think Solidity 0.5 they did

**Comment by jacqueswww** [comment]
@fubuloubu not sure what you mean? inling instead?

**Comment by fubuloubu** [comment]
Yeah, I believe the ABI decoder rewrite eliminated most of the use of RLP and turned into an online feature to save gas on external calls and such.

Something to put on the roadmap for release, it would be huge UX improvement

**Comment by jacqueswww** [comment]
@fubuloubu Ah OK, let's get this function working first. Then we can worry about stuff like that.

**Comment by fubuloubu** [comment]
@jacqueswww I was wrong about this in my initial comment, I am in favor of this if you could rebase.

**Comment by fubuloubu** [comment]
Please rebase/refactor this work and reopen the PR when you're ready

**Pull request closed without merging**
