### PR TITLE
feat: build for aarch64

### PR DESCRIPTION
**Pull request by kelvinfan001**
### What I did

Edit `Makefile` to specify target arch as `universal2` for pyinstaller.

Note: Pending fix in https://github.com/actions/virtual-environments/issues/4133.

fixes https://github.com/vyperlang/vyper/issues/3305

### How I did it

Add `--target-architecture=universal2` in the `make freeze` rule for macOS. 

xref: https://github.com/vyperlang/vyper/discussions/2675#discussioncomment-2230879

### How to verify it

Run the workflow to build artifacts.

### Description for the changelog

Create official binary releases for aarch64 machines.

### Cute Animal Picture

AdobeStock_209028852

### CODE REVIEW

**Comment by charles-cooper** [comment]
note: this would break current `macos-latest` in the unix build matrix. see e.g. https://github.com/charles-cooper/vyper/runs/5401409429?check_suite_focus=true
Screenshot from 2022-03-02 20-15-52

we will have to wait for the fix in https://github.com/actions/virtual-environments/issues/4133 to be merged.

**Comment by charles-cooper** [comment]
another issue seems to be that the pycryptodome `.so` is not a fat binary even when python is
https://github.com/charles-cooper/vyper/runs/5403151996?check_suite_focus=true#step:3:627
Screenshot from 2022-03-02 22-55-35

**Comment by charles-cooper** [comment]
> another issue seems to be that the pycryptodome `.so` is not a fat binary even when python is https://github.com/charles-cooper/vyper/runs/5403151996?check_suite_focus=true#step:3:627 Screenshot from 2022-03-02 22-55-35

it needs to be built from source - https://github.com/charles-cooper/vyper/commit/c47687a5bca4250560378edb840282bf62dbcfa0

**Comment by charles-cooper** [comment]
@kelvinfan001 looks like the upstream issue was fixed! do you mind if i update this PR or would you like to work on it?

**Comment by kelvinfan001** [comment]
@charles-cooper thanks for the update! Feel free to update the PR, as I am no longer working on this.

**Comment by charles-cooper** [comment]
blocked on https://github.com/actions/setup-python/issues/439

**Comment by asafyish** [comment]
Any update on this ? Almost all new macbooks are M1 & M2 and we still don't have support for it, which is very wierd since the entire project is in python.

**Review by fubuloubu — APPROVED** [review]

**Comment by fubuloubu** [comment]
Seems like all blockers are resolved, will let @charles-cooper do a final review and merge

**Comment by charles-cooper** [comment]
I don't think the blockers were resolved, there was some issue with universal2 images upstream. In any case the build needs to be revisited

**Comment by charles-cooper** [comment]
this seems to be working now, see https://github.com/vyperlang/vyper/actions/runs/5014440028/jobs/8988693913

**Pull request merged**
