### PR TITLE
fix[codegen]: bounds check for signed index accesses

### PR DESCRIPTION
**Pull request by charles-cooper**
### What I did
fix https://github.com/vyperlang/vyper/issues/3762

### Commit message

Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../master/docs/style-guide.rst#best-practices-1) for what we would ideally like to see in a commit message.)

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by trocher — COMMENTED** [review]
Would it make more sense to prevent indexing with signed types entirely or is it something that should be possible?

**Review by trocher — COMMENTED** [review]
The order of the args of `clamp2` seems incorrect and should probably be instead `0, ix, bound, ix.typ.is_signed`

Additionally, even with the other order, the check is incorrect for signed integer types when the array's size is greater than or equal to ``2**255``.  `[sle, arg, hi]` performs a signed comparison but `hi`, the length of the array is an unsigned integer interpreted as a signed integer.

For example, compiling:

```vyper
arr: public(uint256[max_value(uint256)-1])

@external

def foo():
    self.arr[1] = 3
```

raises 

```bash
vyper.exceptions.StaticAssertionException: assertion found to fail at compile time. (hint: did you mean `raise`?) [assert,
  [and,
    [sge, 1 <1>, 0],
    [sle,
      1 <1>,
      115792089237316195423570985008687907853269984665640564039457584007913129639934]]]
```

**Comment by charles-cooper** [comment]
> The order of the args of `clamp2` seems incorrect and should probably be instead `0, ix, bound, ix.typ.is_signed`

ah sorry, i should have marked as draft until i have tests passing

> Additionally, even with the other order, the check is incorrect for signed integer types when the array's size is greater than or equal to `2**255`. `[sle, arg, hi]` performs a signed comparison but `hi`, the length of the array is an unsigned integer interpreted as a signed integer.
> 
> For example, compiling:
> 
> ```vyper
> arr: public(uint256[max_value(uint256)-1])
> 
> @external
> 
> def foo():
>     self.arr[1] = 3
> ```
> 
> raises
> 
> ```shell
> vyper.exceptions.StaticAssertionException: assertion found to fail at compile time. (hint: did you mean `raise`?) [assert,
>   [and,
>     [sge, 1 <1>, 0],
>     [sle,
>       1 <1>,
>       115792089237316195423570985008687907853269984665640564039457584007913129639934]]]
> ```

**Review by cyberthirst — APPROVED** [review]

**Review by trocher — COMMENTED** [review]
LGTM :)

**Pull request merged**
