### PR TITLE
chore: run `black` + `isort`

### PR DESCRIPTION
**Pull request by skellet0r**
# What I did

Ran `black` + `isort` via `pre-commit run --all`

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]

**Review by charles-cooper — CHANGES_REQUESTED** [review]
This isn't consistent with `make lint`. When I run `make lint`, I get a bunch of files changed like this

```

reformatted /home/charles/vyper/vyper/semantics/types/function.py
reformatted /home/charles/vyper/vyper/semantics/validation/utils.py
reformatted /home/charles/vyper/vyper/lll/compile_lll.py
reformatted /home/charles/vyper/vyper/semantics/validation/module.py
reformatted /home/charles/vyper/vyper/semantics/validation/local.py
reformatted /home/charles/vyper/vyper/old_codegen/parser_utils.py
reformatted /home/charles/vyper/vyper/old_codegen/expr.py
reformatted /home/charles/vyper/vyper/builtin_functions/functions.py
All done! ✨ 🍰 ✨
59 files reformatted, 291 files left unchanged.
```

**Comment by charles-cooper** [comment]
> This isn't consistent with make lint. When I run make lint, I get a bunch of files changed like this

@skellet0r I looked into this and found that the reason your formatter is working differently is because you're on a different version of black. So I think this PR is ok but also as part of the PR we should constrain the version of black, so in the future we wouldn't be surprised by different versions of black producing different output.

**Comment by skellet0r** [comment]
> your formatter is working differently is because you're on a different version of black
Ah, I made sure to update in #2464

https://github.com/vyperlang/vyper/blob/8a23febbb2d523f3701f9a7d0aaf361c104a2a37/.pre-commit-config.yaml#L9
https://github.com/vyperlang/vyper/blob/8a23febbb2d523f3701f9a7d0aaf361c104a2a37/setup.py#L24
May be just your venv ser ?

@charles-cooper back to you

**Review by charles-cooper — APPROVED** [review]
LGTM, thanks

**Pull request merged**
