### PR TITLE
feat: implement skip_contract_check kwarg

### PR DESCRIPTION
**Pull request by charles-cooper**
### What I did
Implement #2550 

### How I did it
Pretty straightforward, thread the argument through typechecker and codegen

### How to verify it
See tests

### Description for the changelog
Add `omit_contract_check` kwarg as an external call option

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by charles-cooper** [comment]
@transmissions11 up for review if you have any feedback before this gets merged

**Comment by transmissions11** [comment]
`omit_contract_check` is a bit verbose but otherwise this looks great 👍

**Review by fubuloubu — APPROVED** [review]

**Comment by charles-cooper** [comment]
> `omit_contract_check` is a bit verbose but otherwise this looks great +1

any alternatives? open to suggestions

**Comment by transmissions11** [comment]
`no_code_check`?

**Comment by charles-cooper** [comment]
I think we are going to go with `skip_contract_check`. (`contract` instead of `code` because sometimes it's a check on `returndatasize` instead of `extcodesize`).

**Review by fubuloubu — APPROVED** [review]

**Pull request merged**
