### PR TITLE
Fix/disallow nonreentrant decorator on constructor

### PR DESCRIPTION
**Pull request by skellet0r**
### What I did

Simple fix in module level validation. When visiting all the functions, just check if the constructor has the nonreentrant attribute set to a value other than `None`.

Fix: #1755 

### How I did it

Added a check in the module validation stage.

### How to verify it

- Check the test + the line change

### Description for the changelog

- fix: disallow nonreentrant decorator on constructor

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by charles-cooper — COMMENTED** [review]
Nice. One thing I noticed is that the error message highlights the `__init__` function rather than the `nonreentrant` decorator. Do you think it's worth highlighting the decorator instead?

Screenshot from 2021-08-18 13-01-03

**Comment by skellet0r** [comment]
hmmm ... so I could see the case of highlighting either or, but I think for new users in particular, highlighting the decorator will be more clear (even though the message on the exception states it's not allowed on the constructor) 

In any case, tl;dr -> I'll switch it to highlight the decorator instead

**Comment by charles-cooper** [comment]
> hmmm ... so I could see the case of highlighting either or, but I think for new users in particular, highlighting the decorator will be more clear (even though the message on the exception states it's not allowed on the constructor)
> 
> In any case, tl;dr -> I'll switch it to highlight the decorator instead

I looked briefly at how one would do this and I'm not sure it's worth the refactoring work. Can you take a look and try to make a judgment call on whether it's worth it?

**Comment by charles-cooper** [comment]
> I looked briefly at how one would do this and I'm not sure it's worth the refactoring work. Can you take a look and try to make a judgment call on whether it's worth it?

Otherwise -- if we highlight the function signature line, not really the end of the world

**Comment by skellet0r** [comment]
oh lol, I just moved the logic over to the contract function generation, when we do the nonreentrant usage validation

**Review by charles-cooper — APPROVED** [review]
that was easy. thanks!

**Pull request merged**
